version: '2'
services:
  firebird-h01v01:
    environment:
      - AARDVARK=http://localhost:5678
      - CASSANDRA_CONTACT_POINTS=127.0.0.1,127.0.1.1
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASS=cassandra
      - CASSANDRA_KEYSPACE=lcmap_changes_local
      - DRIVER_HOST=${HOSTNAME}
      - INITIAL_PARTITION_COUNT=1
      - LOG_LEVEL=WARN
      - MESOS_USER=mesos
      - MESOS_PASS=mesos
      - MESOS_ROLE=mesos
      - PRODUCT_PARTITION_COUNT=1
      - SPARK_MASTER=mesos:///localhost:7077
      - SPARK_EXECUTOR_IMAGE=firebird.2017.04.25
      - SPARK_EXECUTOR_CORES=1
      - SPARK_EXECUTOR_FORCE_PULL=false
      - SPARK_TOTAL_EXECUTOR_CORES=1000
      - STORAGE_PARTITION_COUNT=1
    ports:
      - "4040:4040"
    volumes:
      - .:/code

    command: spark-submit --py-files file:///releases/pyccd/v2017.06.20.zip firebird save -p seglength --acquired 1980-01-01/2016-12-12 -d -b (11231,32143),(23423,342323)
